// models/User.js
import mongoose from "mongoose";
import { DEFAULT_AVATARS } from "../utils/defaultAvatars.js";

const userSchema = new mongoose.Schema({
  firstName: String,
  lastName: String,
  email: { type: String, unique: true },
  phoneNumber: { type: String, default: "" },
  profileImage: { type: String, default: DEFAULT_AVATARS[0].url },
  avatarType: { type: String, enum: ["default", "custom"], default: "default" },
  password: String,
  role: { type: String, enum: ["user", "admin", "driver"], default: "user" },
  fullName: { type: String, default: "" },
  vehicleNumber: { type: String, default: "" },
  vehicleType: { type: String, default: "" },
  district: { type: String, default: "" },
  status: { type: String, default: "NOT CHECKED IN" },
  isCheckedIn: { type: Boolean, default: false },
  checkedInAt: { type: Date, default: null },
  checkedOutAt: { type: Date, default: null },
  lastLocation: {
    latitude: { type: Number, default: null },
    longitude: { type: Number, default: null },
    accuracy: { type: Number, default: null },
    speed: { type: Number, default: null },
    heading: { type: Number, default: null },
    updatedAt: { type: Date, default: null },
    area: { type: String, default: "" },
    road: { type: String, default: "" },
    district: { type: String, default: "" },
    state: { type: String, default: "" },
    postcode: { type: String, default: "" },
    fullAddress: { type: String, default: "" },
  },
  tracking: {
    isOnline: { type: Boolean, default: false },
    latitude: { type: Number, default: null },
    longitude: { type: Number, default: null },
    accuracy: { type: Number, default: null },
    speed: { type: Number, default: null },
    heading: { type: Number, default: null },
    lastUpdated: { type: Date, default: null },
    checkedInAt: { type: Date, default: null },
    checkedOutAt: { type: Date, default: null },
    area: { type: String, default: "" },
    road: { type: String, default: "" },
    district: { type: String, default: "" },
    state: { type: String, default: "" },
    postcode: { type: String, default: "" },
    fullAddress: { type: String, default: "" },
  },
  currentCheckInId: { type: mongoose.Schema.Types.ObjectId, ref: "DriverCheckIn", default: null },
  driverId: { type: mongoose.Schema.Types.ObjectId, ref: "Driver", default: null },
  otp: String,
  otpExpiresAt: Date,
  isVerified: { type: Boolean, default: false },
}, { timestamps: true });

export default mongoose.model("User", userSchema);